// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Paulo Ferreira",
            "email": "jr@live.at"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/number": {
            "get": {
                "description": "Retrieve information for all numbers",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all numbers",
                "responses": {
                    "200": {
                        "description": "Successfully retrieved all numbers",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Save a number to the collection",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Save number",
                "parameters": [
                    {
                        "format": "number",
                        "description": "Number to be saved",
                        "name": "number",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Number saved successfully",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Failed to parse request body, number not found or not a valid string in the JSON body, or invalid number format",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/number/{number}": {
            "get": {
                "description": "Retrieve information for a specific number",
                "produces": [
                    "application/json"
                ],
                "summary": "Get number information",
                "parameters": [
                    {
                        "type": "integer",
                        "format": "number",
                        "description": "Number to retrieve information for",
                        "name": "number",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully retrieved number information",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Invalid number format in the URL or number not found in the URL",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Number not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "api/v1",
	Schemes:          []string{},
	Title:            "Numeric Type API",
	Description:      "The NumericTypeService API categorizes and manages numeric values. The RESTful endpoints allow clients to store, retrieve, and query numeric values in memory.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
